gem_test_runner:
  image: codeguru/ruby:2.3.1-alpine-3.4
  container_name: gem_test_runner
  command: bash -c "while true; do echo 'Container is running...'; sleep 2; done"
  volumes:
      - ../:/gem_src